### ISSUE TITLE
When is the website being (re-)built?

### ISSUE THREAD

**Issue by sophokles73** [eclipse-sdv-blueprints/blueprints-website#1]
I can only see a GitHub workflow for publishing the website to GH pages but when is the webiste actually being built?

**Comment by nacidai** [comment]
The website can be rebuild in two ways:

1.  When a commit is pushed into this repository (main branch)
2. When the GitHub action is manually triggered by a member of this project. (Deploy to GitHub Pages)
     (blueprints-website > Actions > Run Workflow (from the main brach)
       https://github.com/eclipse-sdv-blueprints/blueprints-website/actions/workflows/deploy.yml

Running the "Deploy to GitHub Pages" action will also pull all the updates from connected blueprints projects (i.e. fleet-management) and update the generated website.  The code for automatically generated ("static") website is kept under the gh-pages branch and deployed to github pages.

The connected projects maintain their own docs, pages and others assets( images etc.)  files. The location can be arbitrary but for the fleet management example I chose docs/  img/ folders at the root of the repository.


The automatically assigned website URL is: 

    https://eclipse-sdv-blueprints.github.io/blueprints-website/

I will open a request with eclipse EMO (@eclipsewebmaster ) to define a  CNAME record with the eclipse.org domain (sdv-blueprints.eclipse.org)

I hope this answers your question, and my apologies for the delayed response due to summer holidays
